version: '3'
services:
  web:
    container_name: fangfangfang
    build: ./
    volumes:
      - ./server:/server
    ports:
      - '56732:80'
    environment:
      - FLASK_APP=main.py
      - FLASK_DEBUG=1
      - 'RUN=python3 main.py'
