"""NOTE: This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).

Do not edit the file manually.
"""

import connexion

from fangfangfang.models.defang_request import DefangRequest  # noqa: E501
from fangfangfang.models.defang_response import DefangResponse  # noqa: E501
from fangfangfang.models.refang_request import RefangRequest  # noqa: E501
from fangfangfang.models.refang_response import RefangResponse  # noqa: E501
from fangfangfang.controllers.impl import default_controller_impl


def defang(body):  # noqa: E501
    """Defang content

     # noqa: E501

    :param body: 
    :type body: dict | bytes

    :rtype: DefangResponse
    """
    if connexion.request.is_json:
        body = DefangRequest.from_dict(connexion.request.get_json())  # noqa: E501
    return default_controller_impl.defang(body)


def refang(body):  # noqa: E501
    """Refang content

     # noqa: E501

    :param body: 
    :type body: dict | bytes

    :rtype: RefangResponse
    """
    if connexion.request.is_json:
        body = RefangRequest.from_dict(connexion.request.get_json())  # noqa: E501
    return default_controller_impl.refang(body)
