openapi: '3.0.2'

info:
  title: 'Fang Fang Fang'
  description: 'Defangs and refangs URLs'
  version: '1.0.0'
  contact:
    name: 'GitHub'
    url: 'https://github.com/nryang/fangfangfang'
  license:
    name: 'MIT'
    url: 'https://github.com/nryang/fangfangfang/blob/master/LICENSE.md'

servers:
- url: 'http://localhost:56732/api'
  description: 'Local'

paths:
  /defang:
    post:
      summary: 'Defang content'
      operationId: 'defang'
      x-codegen-request-body-name: 'body'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DefangRequest'
      responses:
        '200':
          description: 'Success response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DefangResponse'
  /refang:
    post:
      summary: 'Refang content'
      operationId: 'refang'
      x-codegen-request-body-name: 'body'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefangRequest'
      responses:
        '200':
          description: 'Success response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RefangResponse'

components:
  schemas:
    Model:
      type: 'string'
      enum: ['homoglyph']
      default: 'homoglyph'
      format: 'model'
      description: |
        The model to use for defanging or refanging. The default and currently supported model is `homoglyph`.
        | Model | Description |
        |-----|-----|
        | homoglyph | Uses homoglyphs to make links unclickable but readable. |
    DefangRequest:
      type: 'object'
      properties:
        model:
          $ref: '#/components/schemas/Model'
        contents:
          type: 'array'
          items:
            type: 'string'
            example: 'The quick brown fox.com jumps over the lazy dog.meow'
      required:
        - 'contents'
    DefangResponse:
      type: 'object'
      properties:
        defanged_contents:
          type: 'array'
          items:
            type: 'string'
            example: 'The quick brown ſᴏ×․ᴄᴏm jumps over the lazy ⅆᴏƍ․m℮ᴏɯ'
      required:
        - 'defanged_contents'
    RefangRequest:
      type: 'object'
      properties:
        model:
          $ref: '#/components/schemas/Model'
        contents:
          type: 'array'
          items:
            type: 'string'
            example: 'The quick brown ſᴏ×․ᴄᴏm jumps over the lazy ⅆᴏƍ․m℮ᴏɯ'
      required:
        - 'contents'
    RefangResponse:
      type: 'object'
      properties:
        refanged_contents:
          type: 'array'
          items:
            type: 'string'
            example: 'The quick brown fox.com jumps over the lazy dog.meow'
      required:
        - 'refanged_contents'
