#!/usr/bin/env python3

"""NOTE: This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).

Do not edit the file manually.
"""

import connexion

from fangfangfang import encoder


def main():
    app = connexion.App(__name__, specification_dir='./openapi/')
    app.app.json_encoder = encoder.JSONEncoder
    app.add_api('openapi.yaml',
                arguments={'title': 'Fang Fang Fang'},
                pythonic_params=True)
    app.run(port=56732)


if __name__ == '__main__':
    main()
