# coding: utf-8
"""NOTE: This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).

Do not edit the file manually.
"""

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from server.models.base_model_ import Model
from server import util


class DefangResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, defanged_contents=None):  # noqa: E501
        """DefangResponse - a model defined in OpenAPI

        :param defanged_contents: The defanged_contents of this DefangResponse.  # noqa: E501
        :type defanged_contents: List[str]
        """
        self.openapi_types = {
            'defanged_contents': List[str]
        }

        self.attribute_map = {
            'defanged_contents': 'defanged_contents'
        }

        self._defanged_contents = defanged_contents

    @classmethod
    def from_dict(cls, dikt) -> 'DefangResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The DefangResponse of this DefangResponse.  # noqa: E501
        :rtype: DefangResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def defanged_contents(self):
        """Gets the defanged_contents of this DefangResponse.


        :return: The defanged_contents of this DefangResponse.
        :rtype: List[str]
        """
        return self._defanged_contents

    @defanged_contents.setter
    def defanged_contents(self, defanged_contents):
        """Sets the defanged_contents of this DefangResponse.


        :param defanged_contents: The defanged_contents of this DefangResponse.
        :type defanged_contents: List[str]
        """
        if defanged_contents is None:
            raise ValueError("Invalid value for `defanged_contents`, must not be `None`")  # noqa: E501

        self._defanged_contents = defanged_contents
