# coding: utf-8
"""NOTE: This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).

Do not edit the file manually.
"""

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from server.models.base_model_ import Model
from server import util


class RefangResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, refanged_contents=None):  # noqa: E501
        """RefangResponse - a model defined in OpenAPI

        :param refanged_contents: The refanged_contents of this RefangResponse.  # noqa: E501
        :type refanged_contents: List[str]
        """
        self.openapi_types = {
            'refanged_contents': List[str]
        }

        self.attribute_map = {
            'refanged_contents': 'refanged_contents'
        }

        self._refanged_contents = refanged_contents

    @classmethod
    def from_dict(cls, dikt) -> 'RefangResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The RefangResponse of this RefangResponse.  # noqa: E501
        :rtype: RefangResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def refanged_contents(self):
        """Gets the refanged_contents of this RefangResponse.


        :return: The refanged_contents of this RefangResponse.
        :rtype: List[str]
        """
        return self._refanged_contents

    @refanged_contents.setter
    def refanged_contents(self, refanged_contents):
        """Sets the refanged_contents of this RefangResponse.


        :param refanged_contents: The refanged_contents of this RefangResponse.
        :type refanged_contents: List[str]
        """
        if refanged_contents is None:
            raise ValueError("Invalid value for `refanged_contents`, must not be `None`")  # noqa: E501

        self._refanged_contents = refanged_contents
