"""NOTE: This file is auto generated by OpenAPI Generator (https://openapi-generator.tech).

Do not edit the file manually.
"""

import connexion

from server.models.defang_request import DefangRequest  # noqa: E501
from server.models.defang_response import DefangResponse  # noqa: E501
from server.models.refang_request import RefangRequest  # noqa: E501
from server.models.refang_response import RefangResponse  # noqa: E501
from server.controllers.impl import default_controller_impl


def defang(defang_request):  # noqa: E501
    """Defang content

     # noqa: E501

    :param defang_request: 
    :type defang_request: dict | bytes

    :rtype: DefangResponse
    """
    if connexion.request.is_json:
        defang_request = DefangRequest.from_dict(connexion.request.get_json())  # noqa: E501
    return default_controller_impl.defang(defang_request)


def refang(refang_request):  # noqa: E501
    """Refang content

     # noqa: E501

    :param refang_request: 
    :type refang_request: dict | bytes

    :rtype: RefangResponse
    """
    if connexion.request.is_json:
        refang_request = RefangRequest.from_dict(connexion.request.get_json())  # noqa: E501
    return default_controller_impl.refang(refang_request)
